app:
  server-url: http://localhost:8080

spring:
  application:
    name: ai-personal-finance

  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${app.server-url}/api/public/user/login/oauth2/google
            scope:
              - email
              - profile

  jpa:
    open-in-view: false

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
# jwt config
jwt:
  issuer: https://github.com/jhg507677
  admin_secret: secretAdmin123secretAdmin123secretAdmin123secretAdmin12
  user_secret: secretUser123secretUser123secretUser123secretUser12
  access_expire_time: 18000
  refresh_expire_time: 1800000